# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Desc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Metode import Ui_Form6
class Ui_Form5(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(623, 407)
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.pushButton_6.setStyleSheet("background-color: rgb(68, 68, 68);")
        self.pushButton_6.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-left-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(50, 20, 521, 361))
        self.widget.setStyleSheet("background-color: rgb(108, 108, 108);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(-51, -21, 621, 401))
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:45, stop:0 rgba(144, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(400, 130, 151, 81))
        self.label_2.setStyleSheet("background-image: url(:/Background/BG/1.jpg);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Background/BG/2.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(400, 40, 151, 81))
        self.label.setStyleSheet("background-image: url(:/Background/BG/1.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Background/BG/1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(70, 40, 321, 171))
        self.label_3.setStyleSheet("background-image: url(:/Background/BG/Pamali.jpg);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Background/BG/Parakacuk.JPG"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit.setGeometry(QtCore.QRect(70, 220, 481, 71))
        self.textEdit.setStyleSheet("background-color: rgb(68, 68, 68);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 340, 91, 31))
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(108, 108, 108);\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/list.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.splitter = QtWidgets.QSplitter(self.widget_2)
        self.splitter.setGeometry(QtCore.QRect(130, 300, 230, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setStyleSheet("background-color: rgb(108, 108, 108);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(108, 108, 108);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(108, 108, 108);")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(70, 303, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(450, 340, 91, 31))
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(108, 108, 108);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/shopping-cart.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.beli)

        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 631, 411))
        self.widget_3.setStyleSheet("background-color: rgb(68, 68, 68);")
        self.widget_3.setObjectName("widget_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.pushButton_7.setStyleSheet("background-color: rgb(68, 68, 68);")
        self.pushButton_7.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.widget_3.raise_()
        self.pushButton_6.raise_()
        self.widget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def beli(self):
        self.Form = QtWidgets.QDialog()
        self.ui = Ui_Form6()
        self.ui.setupUi(self.Form)
        self.Form.show()
        Form.hide()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ffffff;\">Parakacuk bercerita tentang persahabatan, kekacauan, romansa, dan perselisihan antar geng sekolah. Kalahkan geng musuh, Rebut wilayah mereka, Dan jadilah penguasa Sekolah di SMA Terkuat di sini.</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Form", "WISHLIST"))
        self.pushButton_2.setText(_translate("Form", "Open World"))
        self.pushButton_3.setText(_translate("Form", "Education"))
        self.pushButton.setText(_translate("Form", "Bar-Bar"))
        self.label_5.setText(_translate("Form", "GENRE : "))
        self.pushButton_5.setText(_translate("Form", "Pembelian"))
import BG
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form5()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
