# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Library1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form4(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(634, 481)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        Form.setStyleSheet("QWidget#Form{\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:45, stop:0 rgba(144, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))\n"
"}")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, -10, 101, 491))
        self.widget.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.widget.setObjectName("widget")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 100, 81, 23))
        self.pushButton_4.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font-color : rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 130, 81, 23))
        self.pushButton_6.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"color: rgb(255, 255, 255);\n"
"font-color : rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 190, 81, 23))
        self.pushButton_5.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"color: rgb(255, 255, 255);\n"
"font-color : rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(10, 230, 81, 23))
        self.pushButton.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 160, 81, 23))
        self.pushButton_3.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"color: rgb(255, 255, 255);\n"
"font-color : rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 61, 61))
        self.label_11.setStyleSheet("background-image: url(:/Background/BG/Deafult-Profile-Pitcher.png);")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/Background/BG/Deafult-Profile-Pitcher.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 450, 81, 23))
        self.pushButton_2.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"color: rgb(255, 255, 255);\n"
"font-color : rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(310, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(337, 100, 111, 131))
        self.widget_3.setStyleSheet("image: url(:/BG1/BG/d.jpeg);\n"
"\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(210, 240, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(370, 240, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(490, 70, 111, 181))
        self.frame_4.setStyleSheet("image: url(:/BG1/BG/e.jpeg);")
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(510, 240, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setGeometry(QtCore.QRect(180, 280, 121, 131))
        self.widget_4.setStyleSheet("image: url(:/BG1/BG/a.jpeg);")
        self.widget_4.setObjectName("widget_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(210, 420, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(320, 420, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setGeometry(QtCore.QRect(340, 280, 111, 131))
        self.widget_5.setStyleSheet("image: url(:/BG1/BG/b.jpeg);")
        self.widget_5.setObjectName("widget_5")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(170, 100, 131, 131))
        self.widget_2.setStyleSheet("image: url(:/BG1/BG/c.jpeg);")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(110, 30, 31, 31))
        self.pushButton_7.setStyleSheet("background-color: rgb(68, 68, 68);")
        self.pushButton_7.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-left-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(110, 70, 31, 31))
        self.pushButton_8.setStyleSheet("background-color: rgb(68, 68, 68);")
        self.pushButton_8.setText("")
        self.pushButton_8.clicked.connect(self.home)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setObjectName("pushButton_8")


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def home(self):
        self.Form = QtWidgets.QDialog()
        from Tampilan import Ui_Form1
        self.ui = Ui_Form1()
        self.ui.setupUi(self.Form)
        self.Form.show()
        Form.hide()
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_4.setToolTip(_translate("Form", "<html><head/><body><p>Profil</p></body></html>"))
        self.pushButton_4.setText(_translate("Form", "Profil"))
        self.pushButton_6.setText(_translate("Form", "My Game"))
        self.pushButton_5.setText(_translate("Form", "Sell"))
        self.pushButton.setText(_translate("Form", "Setting"))
        self.pushButton_3.setText(_translate("Form", "Shop"))
        self.pushButton_2.setText(_translate("Form", "About"))
        self.label.setText(_translate("Form", "LIBRARY"))
        self.label_2.setText(_translate("Form", "DreadOut"))
        self.label_3.setText(_translate("Form", "Pamali"))
        self.label_4.setText(_translate("Form", "Motte Island"))
        self.label_5.setText(_translate("Form", "Nusakana"))
        self.label_6.setText(_translate("Form", "Celestian Tales: Old North"))
import BG
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form4()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
